<?php // DO NOT EDIT THIS FILE
$cache=array (
  'items_by_id' => 
  array (
    1 => 
    array (
      'id' => '1',
      'project' => '1',
      'title_src' => 'Adam',
      'title' => 'Adam',
      'desc_src' => '',
      'desc' => '',
      'order' => '0',
      'date_added' => NULL,
      'last_updated' => '2010-01-26 14:17:40',
      'year' => '2010',
    ),
  ),
  'items_by_project' => 
  array (
    1 => 
    array (
      0 => 
      array (
        'id' => '1',
        'project' => '1',
        'title_src' => 'Adam',
        'title' => 'Adam',
        'desc_src' => '',
        'desc' => '',
        'order' => '0',
        'date_added' => NULL,
        'last_updated' => '2010-01-26 14:17:40',
        'year' => '2010',
      ),
    ),
  ),
  'projects' => 
  array (
    1 => 
    array (
      'title' => 'Aviator&nbsp;Project',
      'title_src' => 'Aviator Project',
    ),
  ),
);
?>